apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-games
  labels:
    app: browser-games
spec:
  replicas: 2
  selector:
    matchLabels:
      app: browser-games
  template:
    metadata:
      labels:
        app: browser-games
    spec:
      containers:
      - name: browser-games
        image: browser-games:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
