apiVersion: v1
kind: Service
metadata:
  name: browser-games
  labels:
    app: browser-games
    service: browser-games
spec:
  # ClusterIP for Istio (not LoadBalancer)
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http  # Named ports are required for Istio
  selector:
    app: browser-games
